### ISSUE TITLE
wayland / weston on mesa / grate

### ISSUE THREAD

**Issue by jochenjagers** [grate-driver/mesa#9]
Hello,

i try to run weston on a T20 but it won't work.
Is this not supported yet, is it a bug or I'm doing something wrong?

weston log and gdb backtrace:
~~~
[12:41:46.922] weston 3.0.0
               http://wayland.freedesktop.org
               Bug reports to: https://bugs.freedesktop.org/enter_bug.cgi?product=Wayland&component=weston&version=3.0.0
               Build: unknown (not built from git or tarball)
[12:41:46.922] Command line: /usr/bin/weston --tty 4
[12:41:46.922] OS: Linux, 4.19.98, #1 SMP PREEMPT Fri May 15 07:25:02 UTC 2020, armv7l
[12:41:46.922] warning: XDG_RUNTIME_DIR "/tmp/runtime-root" is not configured
correctly.  Unix access mode must be 0700 (current mode is 755),
and must be owned by the user (current owner is UID 0).
Refer to your distribution on how to get it, or
http://www.freedesktop.org/wiki/Specifications/basedir-spec
on how to implement it.
[12:41:46.923] Starting with no config file.
[12:41:46.923] Output repaint window is 7 ms maximum.
[12:41:46.924] Loading module '/usr/lib/libweston-3/drm-backend.so'
[12:41:47.041] initializing drm backend
[12:41:47.059] using /dev/dri/card0
[12:41:47.060] Loading module '/usr/lib/libweston-3/gl-renderer.so'
[12:41:53.464] EGL client extensions: EGL_EXT_client_extensions
               EGL_EXT_device_base EGL_EXT_device_enumeration
               EGL_EXT_device_query EGL_EXT_platform_base
               EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug
               EGL_EXT_platform_wayland EGL_MESA_platform_gbm
               EGL_MESA_platform_surfaceless EGL_EXT_platform_device
[12:41:53.479] warning: neither EGL_EXT_swap_buffers_with_damage or EGL_KHR_swap_buffers_with_damage is supported. Performance could be affected.
[12:41:53.479] EGL_KHR_surfaceless_context available
[12:41:53.485] EGL version: 1.4
[12:41:53.485] EGL vendor: Mesa Project
[12:41:53.485] EGL client APIs: OpenGL OpenGL_ES 
[12:41:53.486] EGL extensions: EGL_ANDROID_blob_cache EGL_EXT_buffer_age
               EGL_EXT_image_dma_buf_import EGL_KHR_cl_event2
               EGL_KHR_config_attribs EGL_KHR_create_context
               EGL_KHR_create_context_no_error EGL_KHR_fence_sync
               EGL_KHR_get_all_proc_addresses EGL_KHR_gl_renderbuffer_image
               EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image
               EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap
               EGL_KHR_no_config_context EGL_KHR_reusable_sync
               EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
               EGL_KHR_wait_sync EGL_MESA_configless_context
               EGL_MESA_drm_image EGL_MESA_image_dma_buf_export
               EGL_MESA_query_driver EGL_WL_bind_wayland_display
[12:41:53.486] GL version: OpenGL ES 2.0 Mesa 19.3.1 (git-eb009ef53c)
[12:41:53.486] GLSL version: OpenGL ES GLSL ES 1.0.16
[12:41:53.486] GL vendor: Grate
[12:41:53.486] GL renderer: Tegra
[12:41:53.486] GL extensions: GL_EXT_blend_minmax GL_EXT_multi_draw_arrays
               GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1
               GL_EXT_texture_format_BGRA8888
               GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24
               GL_OES_element_index_uint GL_OES_fbo_render_mipmap
               GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives
               GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float
               GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_EGL_image
               GL_OES_depth_texture GL_OES_packed_depth_stencil
               GL_AMD_compressed_ATC_texture
               GL_EXT_texture_type_2_10_10_10_REV GL_OES_get_program_binary
               GL_APPLE_texture_max_level GL_EXT_discard_framebuffer
               GL_EXT_read_format_bgra GL_EXT_frag_depth
               GL_NV_fbo_color_attachments GL_OES_EGL_image_external
               GL_OES_EGL_sync GL_OES_vertex_array_object
               GL_ANGLE_texture_compression_dxt3
               GL_ANGLE_texture_compression_dxt5 GL_EXT_unpack_subimage
               GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth
               GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers
               GL_EXT_map_buffer_range GL_KHR_debug
               GL_KHR_texture_compression_astc_ldr
               GL_OES_required_internalformat GL_OES_surfaceless_context
               GL_EXT_separate_shader_objects
               GL_EXT_compressed_ETC1_RGB8_sub_texture
               GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp
               GL_KHR_context_flush_control GL_OES_draw_elements_base_vertex
               GL_OES_texture_border_clamp GL_KHR_no_error
               GL_KHR_texture_compression_astc_sliced_3d
               GL_EXT_texture_compression_s3tc_srgb
               GL_KHR_parallel_shader_compile
[12:41:53.487] GL ES 2 renderer features:
               read-back format: BGRA
               wl_shm sub-image to texture: yes
               EGL Wayland extension: yes
[12:41:53.491] event0  - [12:41:53.491] EP0700M06: [12:41:53.491] is tagged by udev as: Touchscreen
[12:41:53.491] event0  - [12:41:53.491] EP0700M06: [12:41:53.491] device is a touch device
[12:41:53.493] event2  - [12:41:53.493] gpio-keys: [12:41:53.493] is tagged by udev as: Keyboard
[12:41:53.493] event2  - [12:41:53.493] gpio-keys: [12:41:53.493] device is a keyboard
[12:41:53.599] event1  - [12:41:53.599] wm97xx touchscreen: [12:41:53.599] is tagged by udev as: Touchscreen
[12:41:53.599] event1  - [12:41:53.599] wm97xx touchscreen: [12:41:53.599] device is a touch device
[12:41:53.628] Registered plugin API 'weston_drm_output_api_v1' of size 12
[12:41:53.630] Chosen EGL config details:
               RGBA bits: 8 8 8 0
               swap interval range: 1 - 1
[12:41:53.630] Failed to initialize backlight
[12:41:53.631] Output LVDS-1, (connector 41, crtc 40)
               mode 800x480@80.3, preferred, current
[12:41:53.632] Compositor capabilities:
               arbitrary surface rotation: yes
               screen capture uses y-flip: yes
               presentation clock: CLOCK_MONOTONIC, id 1
               presentation clock resolution: 0.000000001 s
[12:41:53.633] Loading module '/usr/lib/weston/desktop-shell.so'
[12:41:53.712] launching '/usr/libexec/weston-keyboard'
[12:41:53.719] launching '/usr/libexec/weston-desktop-shell'
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:217/grate_stream_push_reloc(): drm_tegra_pushbuf_relocate() failed -22
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:209/grate_stream_push_reloc(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:209/grate_stream_push_reloc(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:337/grate_stream_push_words(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:236/grate_stream_push(): Stream status isn't CONSTRUCT
../../../../../../workspace/sources/mesa/src/gallium/drivers/grate/grate_stream.c:288/grate_stream_end(): Stream status isn't CONSTRUCT
could not load cursor 'dnd-move'
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
could not load cursor 'dnd-copy'
could not load cursor 'dnd-none'
xkbcommon: ERROR: Couldn't read Compose file /tmp/compose: Invalid argument
could not create XKB compose table for locale 'C'.  Disabiling compose
xkbcommon: ERROR: Couldn't read Compose file /tmp/compose: Invalid argument
could not create XKB compose table for locale 'C'.  Disabiling compose

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xb642b114 in st_create_texture_sampler_view_from_stobj (glsl130_or_later=false, format=<optimized out>, stObj=0x3a64a0, st=0x82ee0)
    at ../../../../../../workspace/sources/mesa/src/mesa/state_tracker/st_sampler_view.c:551
#2  st_get_texture_sampler_view_from_stobj (st=st@entry=0x82ee0, stObj=stObj@entry=0x3a64a0, samp=samp@entry=0x3a64b4, glsl130_or_later=glsl130_or_later@entry=false, 
    ignore_srgb_decode=ignore_srgb_decode@entry=false) at ../../../../../../workspace/sources/mesa/src/mesa/state_tracker/st_sampler_view.c:595
#3  0xb65180d8 in st_update_single_texture (st=st@entry=0x82ee0, sampler_view=sampler_view@entry=0xbefff158, texUnit=<optimized out>, glsl130_or_later=glsl130_or_later@entry=false, 
    ignore_srgb_decode=ignore_srgb_decode@entry=false) at ../../../../../../workspace/sources/mesa/src/mesa/state_tracker/st_atom_texture.c:93
#4  0xb6518294 in update_textures (st=0x82ee0, shader_stage=PIPE_SHADER_FRAGMENT, prog=0x3b4ff0, sampler_views=0x833b4)
    at ../../../../../../workspace/sources/mesa/src/mesa/state_tracker/st_atom_texture.c:156
#5  0xb65d9804 in st_validate_state (st=st@entry=0x82ee0, pipeline=pipeline@entry=ST_PIPELINE_RENDER) at ../../../../../../workspace/sources/mesa/src/mesa/state_tracker/st_atom.c:261
#6  0xb6523dd8 in prepare_draw (ctx=0x6a7c8, st=0x82ee0) at ../../../../../../workspace/sources/mesa/src/mesa/state_tracker/st_draw.c:132
#7  st_draw_vbo (ctx=ctx@entry=0x6a7c8, prims=<optimized out>, nr_prims=nr_prims@entry=1, ib=0x0, index_bounds_valid=index_bounds_valid@entry=1 '\001', min_index=<optimized out>, min_index@entry=0, 
    max_index=<optimized out>, max_index@entry=3, tfb_vertcount=0x0, stream=0, indirect=0x0) at ../../../../../../workspace/sources/mesa/src/mesa/state_tracker/st_draw.c:184
#8  0xb65c7ea8 in _mesa_draw_arrays (ctx=0x6a7c8, mode=<optimized out>, start=0, count=4, numInstances=1, baseInstance=0, drawID=0) at ../../../../../../workspace/sources/mesa/src/mesa/main/draw.c:374
#9  0xb65c7f5c in _mesa_DrawArrays (mode=6, start=0, count=4) at ../../../../../../workspace/sources/mesa/src/mesa/main/draw.c:531
#10 0xb6b18068 in repaint_region (ev=ev@entry=0x3ab2a8, region=region@entry=0xbefff41c, surf_region=surf_region@entry=0xbefff430) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/gl-renderer.c:661
#11 0xb6b1856c in draw_view (damage=<optimized out>, output=<optimized out>, ev=0xac738) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/gl-renderer.c:826
#12 repaint_views (output=0xbf800000, output@entry=0xac780, damage=0x1e0, damage@entry=0xbefff4b8) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/gl-renderer.c:850
#13 0xb6b18804 in gl_renderer_repaint_output (output=0xac780, output_damage=0x0) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/gl-renderer.c:1145
#14 0xb6baab78 in drm_output_render_gl (damage=0xbefff65c, output=0xac780) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/compositor-drm.c:734
#15 drm_output_render (damage=0xbefff65c, output=0xac780) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/compositor-drm.c:796
#16 drm_output_repaint (output_base=0xac780, damage=0xbefff65c, repaint_data=<optimized out>) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/compositor-drm.c:880
#17 0xb6fa98f0 in weston_output_repaint (repaint_data=<optimized out>, output=<optimized out>) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/compositor.c:2312
#18 weston_output_maybe_repaint (repaint_data=<optimized out>, now=0xb6fcd000, output=<optimized out>) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/compositor.c:2376
#19 output_repaint_timer_handler (data=0x0) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/libweston/compositor.c:2442
#20 0xb6f836f8 in wl_event_source_timer_dispatch (source=0x2e8d8, ep=<optimized out>) at /usr/src/debug/wayland/1.16.0-r0/wayland-1.16.0/src/event-loop.c:236
#21 0xb6f83c80 in wl_event_loop_dispatch (loop=0x2d5a0, timeout=timeout@entry=-1) at /usr/src/debug/wayland/1.16.0-r0/wayland-1.16.0/src/event-loop.c:641
#22 0xb6f82a00 in wl_display_run (display=0x2d530, display@entry=0xb6ff72c8) at /usr/src/debug/wayland/1.16.0-r0/wayland-1.16.0/src/wayland-server.c:1260
#23 0x000143e0 in main (argc=<optimized out>, argv=0xbefffd44) at /usr/src/debug/weston/3.0.0-r0/weston-3.0.0/compositor/main.c:1969
~~~

**Comment by digetx** [comment]
Yes, it's not supported yet.
